data structure in pandas is series(only one column ) and data frame(multiple column)

1.creating DataFrame in pandas

In [4]:
# import pandas library
import pandas as pd
# input data
data={
    "Name":["partha","peter","biswajit"],
    "age":[24,43,22],
    "salary":[20000,40000,21000]
}
# create the above data as data frame 
df = pd.DataFrame(data)

# print the data frame
print(df)

       Name  age  salary
0    partha   24   20000
1     peter   43   40000
2  biswajit   22   21000

read csv file

In [10]:
# read csv file
dataFrame=pd.read_csv("E:/MY PROGRAMMING JOURNEY/CSV FILE/Paris 2024 Olympics_Nations Medals.csv")
print(dataFrame)

    NOC  Gold  Silver  Bronze  Total
0   USA    40      44      42    126
1   CHN    40      27      24     91
2   JPN    20      12      13     45
3   AUS    18      19      16     53
4   FRA    16      26      22     64
..  ...   ...     ...     ...    ...
86  SIN     0       0       1      1
87  CIV     0       0       1      1
88  ROT     0       0       1      1
89  PER     0       0       1      1
90  SVK     0       0       1      1

[91 rows x 5 columns]

2.Exploring data in pandas

In [12]:
# print 10 data from top 
dataFrame.head(10)

   NOC  Gold  Silver  Bronze  Total
0  USA    40      44      42    126
1  CHN    40      27      24     91
2  JPN    20      12      13     45
3  AUS    18      19      16     53
4  FRA    16      26      22     64
5  NED    15       7      12     34
6  GBR    14      22      29     65
7  KOR    13       9      10     32
8  ITA    12      13      15     40
9  GER    12      13       8     33

In [13]:
# print 10 data from bottom
dataFrame.tail(10)

    NOC  Gold  Silver  Bronze  Total
81  PUR     0       0       2      2
82  MAS     0       0       2      2
83  CPV     0       0       1      1
84  QAT     0       0       1      1
85  ZAM     0       0       1      1
86  SIN     0       0       1      1
87  CIV     0       0       1      1
88  ROT     0       0       1      1
89  PER     0       0       1      1
90  SVK     0       0       1      1

In [ ]:
# print data type  and information of the given data
print(dataFrame.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NOC     91 non-null     object
 1   Gold    91 non-null     int64
 2   Silver  91 non-null     int64
 3   Bronze  91 non-null     int64
 4   Total   91 non-null     int64
dtypes: int64(4), object(1)
memory usage: 3.7+ KB
None

In [ ]:
#describe data frame
dataFrame.describe()

            Gold     Silver     Bronze       Total
count  91.000000  91.000000  91.000000   91.000000
mean    3.604396   3.626374   4.208791   11.439560
std     6.990278   6.760421   6.563394   19.694449
min     0.000000   0.000000   0.000000    1.000000
25%     0.000000   0.000000   1.000000    2.000000
50%     1.000000   1.000000   2.000000    5.000000
75%     3.000000   3.000000   5.000000    9.000000
max    40.000000  44.000000  42.000000  126.000000

In [20]:
#find missing value or null value 
dataFrame.isnull()

      NOC   Gold  Silver  Bronze  Total
0   False  False   False   False  False
1   False  False   False   False  False
2   False  False   False   False  False
3   False  False   False   False  False
4   False  False   False   False  False
..    ...    ...     ...     ...    ...
86  False  False   False   False  False
87  False  False   False   False  False
88  False  False   False   False  False
89  False  False   False   False  False
90  False  False   False   False  False

[91 rows x 5 columns]

In [19]:
#total number of missing value as column wish 
dataFrame.isnull().sum()

NOC       0
Gold      0
Silver    0
Bronze    0
Total     0
dtype: int64