data structure in pandas is series(only one column ) and data frame(multiple column)

1.creating DataFrame in pandas

In [18]:
# import pandas library
import pandas as pd
# input data
data={
    "Name":["partha","peter","biswajit"],
    "age":[24,43,22],
    "salary":[20000,40000,21000]
}
# create the above data as data frame 
df = pd.DataFrame(data)

# print the data frame
print(df)

       Name  age  salary
0    partha   24   20000
1     peter   43   40000
2  biswajit   22   21000

read csv file

In [61]:
# read csv file
dataFrame=pd.read_csv("E:/MY PROGRAMMING JOURNEY/CSV FILE/Paris 2024 Olympics_Nations Medals.csv")
print(dataFrame)

    NOC  Gold  Silver  Bronze  Total
0   USA  40.0    44.0      42  126.0
1   CHN  40.0    27.0      24   91.0
2   JPN  20.0    12.0      13   45.0
3   AUS  18.0    19.0      16   53.0
4   FRA  16.0    26.0      22   64.0
..  ...   ...     ...     ...    ...
86  SIN   0.0     0.0       1    1.0
87  CIV   0.0     0.0       1    NaN
88  ROT   0.0     0.0       1    1.0
89  PER   0.0     0.0       1    1.0
90  SVK   0.0     0.0       1    1.0

[91 rows x 5 columns]

2.Exploring data in pandas

In [20]:
# print 10 data from top 
dataFrame.head(10)

   NOC  Gold  Silver  Bronze  Total
0  USA    40      44      42    126
1  CHN    40      27      24     91
2  JPN    20      12      13     45
3  AUS    18      19      16     53
4  FRA    16      26      22     64
5  NED    15       7      12     34
6  GBR    14      22      29     65
7  KOR    13       9      10     32
8  ITA    12      13      15     40
9  GER    12      13       8     33

In [29]:
# print 10 data from bottom
dataFrame.tail(10)

    NOC  Gold  Silver  Bronze  Total
81  PUR     0       0       2      2
82  MAS     0       0       2      2
83  CPV     0       0       1      1
84  QAT     0       0       1      1
85  ZAM     0       0       1      1
86  SIN     0       0       1      1
87  CIV     0       0       1      1
88  ROT     0       0       1      1
89  PER     0       0       1      1
90  SVK     0       0       1      1

In [22]:
# print data type  and information of the given data
print(dataFrame.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NOC     91 non-null     object
 1   Gold    91 non-null     int64
 2   Silver  91 non-null     int64
 3   Bronze  91 non-null     int64
 4   Total   91 non-null     int64
dtypes: int64(4), object(1)
memory usage: 3.7+ KB
None

In [30]:
#describe data frame
dataFrame.describe()

            Gold     Silver     Bronze       Total
count  91.000000  91.000000  91.000000   91.000000
mean    3.604396   3.626374   4.208791   11.439560
std     6.990278   6.760421   6.563394   19.694449
min     0.000000   0.000000   0.000000    1.000000
25%     0.000000   0.000000   1.000000    2.000000
50%     1.000000   1.000000   2.000000    5.000000
75%     3.000000   3.000000   5.000000    9.000000
max    40.000000  44.000000  42.000000  126.000000

In [20]:
#find missing value or null value 
dataFrame.isnull()

      NOC   Gold  Silver  Bronze  Total
0   False  False   False   False  False
1   False  False   False   False  False
2   False  False   False   False  False
3   False  False   False   False  False
4   False  False   False   False  False
..    ...    ...     ...     ...    ...
86  False  False   False   False  False
87  False  False   False   False  False
88  False  False   False   False  False
89  False  False   False   False  False
90  False  False   False   False  False

[91 rows x 5 columns]

In [31]:
#total number of missing value as column wish 
dataFrame.isnull().sum()

NOC       0
Gold      0
Silver    0
Bronze    0
Total     0
dtype: int64

3.Handling Duplicate values in pandas

**duplicates values alweys find uniqe column or primary key

In [32]:
#Identify duplicate value
print(dataFrame.duplicated()) #its provide duplicate value present or not in a row

0     False
1     False
2     False
3     False
4     False
      ...
86    False
87    False
88    False
89    False
90    False
Length: 91, dtype: bool

In [16]:
#Identify duplicate value in a particular column

print(dataFrame["NOC"].duplicated()) # given data frame NOC is a primary key
#true--> present
#fales-->not present

0     False
1     False
2     False
3     False
4     False
      ...
86    False
87    False
88    False
89    False
90    False
Name: NOC, Length: 91, dtype: bool

In [33]:
# calculate total number of duplicate value in a column
print(dataFrame["NOC"].duplicated().sum())

4

In [34]:
#drop duplicate value 
print(dataFrame.drop_duplicates("NOC"))

    NOC  Gold  Silver  Bronze  Total
0   USA    40      44      42    126
1   CHN    40      27      24     91
2   JPN    20      12      13     45
3   AUS    18      19      16     53
4   FRA    16      26      22     64
..  ...   ...     ...     ...    ...
86  SIN     0       0       1      1
87  CIV     0       0       1      1
88  ROT     0       0       1      1
89  PER     0       0       1      1
90  SVK     0       0       1      1

[87 rows x 5 columns]

4.Working with Missing data in pandas

In [62]:
#find missing value or null value 
dataFrame.isnull()

      NOC   Gold  Silver  Bronze  Total
0   False  False   False   False  False
1   False  False   False   False  False
2   False  False   False   False  False
3   False  False   False   False  False
4   False  False   False   False  False
..    ...    ...     ...     ...    ...
86  False  False   False   False  False
87  False  False   False   False   True
88  False  False   False   False  False
89  False  False   False   False  False
90  False  False   False   False  False

[91 rows x 5 columns]

In [63]:
#total number of missing value as column wish 
dataFrame.isnull().sum()

NOC       0
Gold      1
Silver    3
Bronze    0
Total     3
dtype: int64

In [64]:
# calculate total number of missing value in our data set
dataFrame.isnull().sum().sum()

7

In [43]:
# calculate parcentage of missing value present in each column
dataFrame.isnull().sum()/df.shape[0]*100 #[0] are use for calculate number of row only

NOC         0.000000
Gold       33.333333
Silver    100.000000
Bronze      0.000000
Total     100.000000
dtype: float64

In [65]:
# total percentage of missing value present in data set
dataFrame.isnull().sum().sum()/(df.shape[0]* df.shape[1])*100

77.77777777777779

In [66]:
#drop missing value
dataFrame.dropna()

    NOC  Gold  Silver  Bronze  Total
0   USA  40.0    44.0      42  126.0
1   CHN  40.0    27.0      24   91.0
2   JPN  20.0    12.0      13   45.0
3   AUS  18.0    19.0      16   53.0
4   FRA  16.0    26.0      22   64.0
..  ...   ...     ...     ...    ...
85  ZAM   0.0     0.0       1    1.0
86  SIN   0.0     0.0       1    1.0
88  ROT   0.0     0.0       1    1.0
89  PER   0.0     0.0       1    1.0
90  SVK   0.0     0.0       1    1.0

[84 rows x 5 columns]

In [67]:
#replace missing value with any value in full dataframe
import numpy as np

print(dataFrame.replace(np.nan,"hello"))

    NOC  Gold Silver  Bronze  Total
0   USA  40.0   44.0      42  126.0
1   CHN  40.0   27.0      24   91.0
2   JPN  20.0   12.0      13   45.0
3   AUS  18.0   19.0      16   53.0
4   FRA  16.0   26.0      22   64.0
..  ...   ...    ...     ...    ...
86  SIN   0.0    0.0       1    1.0
87  CIV   0.0    0.0       1  hello
88  ROT   0.0    0.0       1    1.0
89  PER   0.0    0.0       1    1.0
90  SVK   0.0    0.0       1    1.0

[91 rows x 5 columns]

In [68]:
# calulate mean of the total column
dataFrame["Total"].mean()

11.647727272727273

In [71]:
#replace missing value in a particular column  with mean value
dataFrame["Total"]=dataFrame["Total"].replace(np.nan,11.64)
print(dataFrame)

# calulate mean
dataFrame["Total"].mean() 
# does not affect the total mean

    NOC  Gold  Silver  Bronze   Total
0   USA  40.0    44.0      42  126.00
1   CHN  40.0    27.0      24   91.00
2   JPN  20.0    12.0      13   45.00
3   AUS  18.0    19.0      16   53.00
4   FRA  16.0    26.0      22   64.00
..  ...   ...     ...     ...     ...
86  SIN   0.0     0.0       1    1.00
87  CIV   0.0     0.0       1   11.64
88  ROT   0.0     0.0       1    1.00
89  PER   0.0     0.0       1    1.00
90  SVK   0.0     0.0       1    1.00

[91 rows x 5 columns]

11.647472527472528

In [73]:
# fill the missing value in backword method
print(dataFrame.fillna(method="bfill"))

    NOC  Gold  Silver  Bronze   Total
0   USA  40.0    44.0      42  126.00
1   CHN  40.0    27.0      24   91.00
2   JPN  20.0    12.0      13   45.00
3   AUS  18.0    19.0      16   53.00
4   FRA  16.0    26.0      22   64.00
..  ...   ...     ...     ...     ...
86  SIN   0.0     0.0       1    1.00
87  CIV   0.0     0.0       1   11.64
88  ROT   0.0     0.0       1    1.00
89  PER   0.0     0.0       1    1.00
90  SVK   0.0     0.0       1    1.00

[91 rows x 5 columns]

C:\Users\PARTHA GAYEN\AppData\Local\Temp\ipykernel_1940\4074791436.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(dataFrame.fillna(method="bfill"))

In [74]:
# fill the missing value in forword method
print(dataFrame.fillna(method="ffill"))

    NOC  Gold  Silver  Bronze   Total
0   USA  40.0    44.0      42  126.00
1   CHN  40.0    27.0      24   91.00
2   JPN  20.0    12.0      13   45.00
3   AUS  18.0    19.0      16   53.00
4   FRA  16.0    26.0      22   64.00
..  ...   ...     ...     ...     ...
86  SIN   0.0     0.0       1    1.00
87  CIV   0.0     0.0       1   11.64
88  ROT   0.0     0.0       1    1.00
89  PER   0.0     0.0       1    1.00
90  SVK   0.0     0.0       1    1.00

[91 rows x 5 columns]

C:\Users\PARTHA GAYEN\AppData\Local\Temp\ipykernel_1940\248532034.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(dataFrame.fillna(method="ffill"))